<a href="https://colab.research.google.com/github/PandukaBandara99/ML-Books/blob/main/Python_Handbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mahela Panduka Bandara ; <br> UG @ Dpt. of Electronic & Electrical Engineering ;<br> University of Peradeniya ;<br> 2023/03 <br><br> Email : e19039@end.pdn.ac.lk <br> LinkedIN : https://www.linkedin.com/in/pandukabandara/

# 2.0 Object Oriented Programming

## 2.1 Introduction

Object-Oriented Programming (OOP) is a programming paradigm that emphasizes the use of objects, which are instances of classes, to structure and organize code. Python fully supports OOP, allowing developers to create classes, define attributes and methods, and create objects based on those classes.

1. **Classes and Objects:**
   - A class is a blueprint that defines the attributes and behavior of an object.
   - To create a class, use the `class` keyword followed by the class name. Inside the class, define attributes and methods.
   - An object is an instance of a class. You can create multiple objects based on a single class.

2. **Attributes:**
   - Attributes are variables associated with a class or object. They hold data that describes the state of the object.
   - Class attributes are shared among all instances of the class, while instance attributes are specific to each object.
   - You can define attributes within the class using the `self` keyword to refer to the instance of the class.

3. **Methods:**
   - Methods are functions defined within a class that perform actions on objects or manipulate object data.
   - Instance methods take the `self` parameter, which represents the instance calling the method.
   - Class methods are defined using the `@classmethod` decorator and take the `cls` parameter, representing the class itself.
   - Static methods are defined using the `@staticmethod` decorator and do not take any specific instance or class parameters.

4. **Inheritance:**
   - Inheritance is a mechanism where a class inherits properties and behavior from another class, called the superclass or base class.
   - The derived class, also known as the subclass or child class, can extend or override the attributes and methods of the base class.
   - In Python, you can define inheritance by specifying the base class in parentheses when creating a new class.

5. **Encapsulation:**
   - Encapsulation is the process of hiding the internal details of a class and providing a public interface for interacting with the class.
   - You can control access to attributes and methods using access specifiers: public (default), private (prefixed with double underscore), and protected (prefixed with single underscore).

6. **Polymorphism:**
   - Polymorphism allows objects of different classes to be treated as objects of a common superclass.
   - It enables methods with the same name to behave differently based on the object type they are invoked on.
   - Polymorphism in Python is achieved through method overriding and method overloading.

OOP in Python provides a structured and modular approach to programming, promoting code reuse, maintainability, and abstraction. By defining classes and objects, you can create organized and flexible code that models real-world entities or abstract concepts.

**Summery:**


| Topic                     | Explanation                                                                 |
|---------------------------|------------------------------------------------------------------------------|
| Classes and Objects       | - Blueprints that define attributes and behavior                               |
|                           | - Objects are instances of classes                                            |
| Attributes                | - Variables associated with classes or objects                                |
|                           | - Class attributes are shared, instance attributes are specific to objects    |
| Methods                   | - Functions defined within classes                                            |
|                           | - Perform actions on objects or manipulate data                              |
| Inheritance               | - Mechanism for inheriting properties and behavior                            |
|                           | - Subclass extends or overrides base class attributes and methods             |
| Encapsulation             | - Hiding internal details and providing a public interface                    |
|                           | - Control access with access specifiers (public, private, protected)          |
| Polymorphism              | - Objects of different classes treated as objects of a common superclass      |
|                           | - Methods with the same name behave differently based on object type          |


##2.2 Classes And Objects



1. **Defining a Class:**
   - To define a class, use the `class` keyword followed by the class name, which typically starts with an uppercase letter.
   - The class can have attributes (variables) and methods (functions) defined within it.
   - Example:
     ```python
     class Car:
         pass
     ```

2. **Creating Objects (Instances):**
   - Objects are instances of a class, created using the class name followed by parentheses.
   - This invokes the class's special method called the constructor (`__init__()`), which initializes the object.
   - Example:
     ```python
     my_car = Car()
     ```

3. **Class Attributes:**
   - Class attributes are variables that are shared among all instances of the class.
   - They are defined within the class but outside of any methods.
   - Class attributes can be accessed using the class name or any object of the class.
   - Example:
     ```python
     class Car:
         wheels = 4

     print(Car.wheels)  # Output: 4
     my_car = Car()
     print(my_car.wheels)  # Output: 4
     ```

4. **Instance Attributes:**
   - Instance attributes are specific to each object (instance) of the class.
   - They are defined within the class's constructor (`__init__()` method) and accessed using the `self` keyword.
   - Example:
     ```python
     class Car:
         def __init__(self, color):
             self.color = color

     my_car = Car("blue")
     print(my_car.color)  # Output: "blue"
     ```

5. **Methods:**
   - Methods are functions defined within a class that perform actions on objects or manipulate object data.
   - They are defined inside the class and can access attributes through the `self` parameter.
   - Example:
     ```python
     class Car:
         def __init__(self, color):
             self.color = color

         def drive(self):
             print("The car is driving.")

     my_car = Car("blue")
     my_car.drive()  # Output: "The car is driving."
     ```

6. **Class and Instance Variables:**
   - Class variables are shared among all instances and can be accessed using the class name or any object.
   - Instance variables are specific to each object and can be accessed using the `self` keyword.
   - Example:
     ```python
     class Car:
         wheels = 4

         def __init__(self, color):
             self.color = color

     print(Car.wheels)  # Output: 4

     my_car = Car("blue")
     print(my_car.color)  # Output: "blue"
     ```

7. **Special Methods:**
   - Special methods (also called magic methods or dunder methods) provide functionality to classes.
   - They are surrounded by double underscores and have predefined names.
   - Examples of special methods include `__init__()` for object initialization, `__str__()` for string representation, `__len__()` for length calculation, etc.



### 2.2.1  Example 1


In [3]:
# Define a class ~> Data Type
class ItemE1:
  pass

# Instsnce & assign properties
item1 = ItemE1()
item1.name = "Phone"
item1.price = 100
item1.quantity = 5

print(type(item1))           #item <data type> ~> <class '__main__.ItemE1'>
print(type(item1.name))      # str
print(type(item1.price))     #int
print(type(item1.quantity))  #int

print(item1.name.upper())

<class '__main__.ItemE1'>
<class 'str'>
<class 'int'>
<class 'int'>
PHONE


## 2.3 self

In object-oriented programming (OOP) in Python, the `self` attribute refers to the instance of a class that is being manipulated or accessed within a method. It is a convention to name the first parameter of instance methods as `self`, although you can choose any valid variable name.


1. Reference to the Instance:
   - When a method is called on an object, the object itself is passed as the first argument implicitly.
   - By convention, this parameter is named `self` to indicate that it refers to the instance of the class.

2. Accessing Instance Attributes:
   - Within a method, you can use the `self` attribute to access instance attributes.
   - Instance attributes are unique to each object and can hold different values.
   - By prefixing the attribute name with `self`, you can access and modify its value.

   Example:
   ```python
   class Car:
       def __init__(self, color):
           self.color = color

       def drive(self):
           print(f"The {self.color} car is driving.")

   my_car = Car("blue")
   my_car.drive()  # Output: "The blue car is driving."
   ```

3. Calling Other Methods:
   - The `self` attribute allows you to call other methods of the same object within a method.
   - You can invoke methods using the `self` attribute followed by the method name and parentheses.

   Example:
   ```python
   class Car:
       def __init__(self, color):
           self.color = color

       def start_engine(self):
           # Perform some actions to start the engine
           print("Engine started.")

       def drive(self):
           self.start_engine()
           print(f"The {self.color} car is driving.")

   my_car = Car("red")
   my_car.drive()
   # Output:
   # "Engine started."
   # "The red car is driving."
   ```


### 2.3.1 Example 2

In [4]:
# Define a class ~> Data Type
class ItemE2:

  '''
  Need to declare self argument since python passes the object(instance)
  itself as the initial argument always. So, other variables comes after that.
  It's nothing to use other name than self but , 'self' keyword is a common
  naming convention.
  '''
  def calculateTotalPrice(self , price , quantity):
    return price*quantity

# Instsnce & assign properties
item2 = ItemE2()
item2.name = "Phone"
item2.price = 1000
item2.quantity = 3

# It passes it self and other two variables to the method
print(item2.calculateTotalPrice(item2.price,item2.quantity))

3000


## 2.4 Class Attributes

Class attributes are variables that are defined within a class but outside of any methods. They are shared among all instances of the class and can be accessed using **either the class name or an instance of the class**. Class attributes are defined at the class level and are the same for all objects of that class.

1. Definition and Access:
   - Class attributes are defined directly within the class body, outside of any methods.
   - They are accessed using the class name or an instance of the class.

2. Shared Among Instances:
   - Class attributes are shared among all instances of the class.
   - When an instance accesses or modifies a class attribute, the change is reflected across all instances.

3. Initialization:
   - Class attributes are typically initialized when they are defined, similar to global variables.
   - They can also be modified or accessed within methods using the class name or the `self` keyword.

4. Visibility:
   - Class attributes are visible to all instances of the class and can be accessed by all instances.
   - They can also be accessed from outside the class using the class name.



### 2.4.1 Example 3

In [5]:
class Car:
    color = "Red"  # Class attribute

    def __init__(self, brand):
        self.brand = brand  # Instance attribute

    def get_color(self):
        return self.color  # Accessing class attribute using self

car1 = Car("Toyota")
car2 = Car("Honda")

print(car1.brand)  # Output: Toyota
print(car2.brand)  # Output: Honda
print(car1.color)  # Output: Red
print(car2.color)  # Output: Red

print(Car.color)  # Output: Red

car1.color = "Blue"
print(car1.color)  # Output: Blue
print(car2.color)  # Output: Red

Toyota
Honda
Red
Red
Red
Blue
Red



In the example, `color` is a class attribute defined within the `Car` class. It is shared among all instances of the class. The `brand` attribute is an instance attribute specific to each instance of the class. The `get_color()` method accesses the class attribute using `self.color`.

Class attributes are useful when need to store data that is shared among all instances of a class, such as default values, constants, or common properties. They provide a way to define and manage data at the class level, ensuring consistency across all instances.

### 2.4.2 Example 4

In [6]:
class ItemX:
  rate = 0.8

  #Recieves it self,name , price value and the quanntity
  def __init__(self,namePassed ,pricePassed,quantityPassed = 0):

    #Assign the properties to the object(self)
    self.name = namePassed
    self.price = pricePassed
    self.quantity = quantityPassed

  def calculatePrice(self):
    return self.price*self.quantity
  def apply_discount(self):
    # Note that class attributes cannot access directly!
    self.price = self.price*self.rate   #or  ItemX.rate ~> Not recomended

#Instance
itemX = ItemX("Laptop",1000,1)

#Calculate and print price
print(f"Price is : {itemX.calculatePrice()}")

#Apply discount
itemX.apply_discount()

#Print value after discount
print(f"Price is : {itemX.calculatePrice()}")

# Update the discount value
itemX.rate = 0.25

#Apply discount
itemX.apply_discount()

#Print value after discount
print(f"Price is : {itemX.calculatePrice()}")

Price is : 1000
Price is : 800.0
Price is : 200.0


##2.5 Magic Methods

Magic methods, also known as special methods or dunder (double underscore) methods, are predefined methods in Python that allows to define behavior for  custom classes. They are surrounded by double underscores at the beginning and end of their names.

|        Method        |                            Explanation                            |
|----------------------|-------------------------------------------------------------------|
| `__init__(self, ...)`    | Initializes an object of a class with specified attributes        |
| `__str__(self)`          | Returns a string representation of the object                     |
| `__repr__(self)`         | Returns a string representation that can be used to recreate the object |
| `__len__(self)`          | Returns the length of the object                                  |
| `__getitem__(self, key)` | Enables accessing an item in the object using square bracket notation |
| `__setitem__(self, key, value)` | Enables setting a value for an item in the object using square bracket notation |
| `__delitem__(self, key)` | Enables deleting an item from the object using the `del` statement |
| `__add__(self, other)`   | Defines behavior for the addition operation (`+`) between objects |
| `__sub__(self, other)`   | Defines behavior for the subtraction operation (`-`) between objects |
| `__eq__(self, other)`    | Defines behavior for equality comparison (`==`) between objects   |
| `__lt__(self, other)`    | Defines behavior for less-than comparison (`<`) between objects   |
| `__gt__(self, other)`    | Defines behavior for greater-than comparison (`>`) between objects |
| `__call__(self, ...)`    | Allows an object to be called as a function                         |


###2.5.1 \_\_init\_\_

**Example**:

In [7]:
class Item3:
  rate = 0.5
  #Recieves it self,name , price value and the quanntity
  def __init__(self,namePassed ,pricePassed,quantityPassed = 0):
    #Assign the properties to the object(self)
    self.name = namePassed
    self.price = pricePassed
    self.quantity = quantityPassed
  def calculatePrice(self):
    return self.price*self.quantity

item3 = Item3("Laptop",1000,1)

print(item3.name)
print(item3.price)
print(item3.quantity)
print(f"Price is : {item3.calculatePrice()}")

print(item3.rate)

Laptop
1000
1
Price is : 1000
0.5


### 2.5.2 \_\_dict\_\_

 `__dict__` attribute is a dictionary that stores the namespace of a class or an instance. It contains all the attributes (variables and methods) defined within the class or associated with the instance as key-value pairs.


1. Class `__dict__`:
   - For a class, `__dict__` contains the class-level attributes, including class variables and methods.
   - It provides a way to access and modify the attributes of the class directly.

2. Instance `__dict__`:
   - For an instance of a class, `__dict__` contains the instance-specific attributes.
   - It includes both the instance variables (attributes) and any attributes inherited from the class.

3. Dictionary Structure:
   - The `__dict__` attribute is implemented as a dictionary, where attribute names are the keys, and the corresponding values are the attribute values.
   - The dictionary allows accessing and manipulating attributes dynamically at runtime.




In [8]:
print(Item3.__dict__) # All the attribiutes for class level
print(item3.__dict__) # All the attribiutes for instance level ~> Note the rate and function does not inclued

{'__module__': '__main__', 'rate': 0.5, '__init__': <function Item3.__init__ at 0x7dd136ee8700>, 'calculatePrice': <function Item3.calculatePrice at 0x7dd136ee8040>, '__dict__': <attribute '__dict__' of 'Item3' objects>, '__weakref__': <attribute '__weakref__' of 'Item3' objects>, '__doc__': None}
{'name': 'Laptop', 'price': 1000, 'quantity': 1}


##2.6 Type Hints

Type hints in Python are a way to specify the expected types of variables, function arguments, and return values. They provide additional information about the types used in your code, which can help improve code readability, maintainability, and enable static type checking.


1. Variable Annotations:
   Annotate variables using the `:` syntax to indicate their expected type.
   ```python
   age: int = 25
   name: str = "John"
   ```

2. Function Annotations:
   Function arguments and return values can be annotated using the `:` syntax.
   ```python
   def greet(name: str) -> str:
       return "Hello, " + name
   ```

3. Optional Types:
   You can indicate that a variable or function argument is optional by using the `typing.Optional` type.
   ```python
   from typing import Optional

   def say_hello(name: Optional[str]) -> str:
       if name:
           return "Hello, " + name
       else:
           return "Hello, stranger"
   ```

4. Union Types:
   Union types allow specifying that a variable or function argument can have multiple possible types.
   ```python
   from typing import Union

   def add(x: Union[int, float], y: Union[int, float]) -> Union[int, float]:
       return x + y
   ```

5. Type Aliases:
   Type aliases provide a way to define custom type names for complex types or to make the code more readable.
   ```python
   from typing import List

   Vector = List[float]

   def scale(scalar: float, vector: Vector) -> Vector:
       return [scalar * num for num in vector]
   ```

Type hints are optional and do not affect the runtime behavior of the code. They are primarily used by static type checkers, such as `mypy`, to analyze the code and detect potential type-related issues.

###2.6.1 Example 5

In [9]:
class Item4:
  #Recieves it self,name , price value and the quanntity
  def __init__(self,namePassed : str ,pricePassed :float ,quantityPassed : int):
    #Assign the properties to the object(self)
    self.name = namePassed
    self.price = pricePassed
    self.quantity = quantityPassed
  def calculatePrice(self) -> float:
    return self.price*self.quantity

item4 = Item4("Laptop",1000,1)

print(item4.name)
print(item4.price)
print(item4.quantity)
print(f"Price is : {item4.calculatePrice()}")

Laptop
1000
1
Price is : 1000


## 2.7 Assert Statement

The `assert` statement is a useful tool in Python for testing assumptions and ensuring that specific conditions are met. It allows to check if a given expression evaluates to `True` and raises an `AssertionError` if the expression evaluates to `False`. The `assert` statement can be used during development to detect logical errors or to validate input/output conditions.

The syntax for using the `assert` statement is as follows:

```python
assert expression, message
```

- The `expression` is the condition that need to be checked. If it evaluates to `True`, the program continues execution as normal. If it evaluates to `False`, an `AssertionError` is raised.
- The optional `message` parameter is an informative string that can be included to provide more details about the assertion.

Some key points about the `assert` statement:

1. Use Cases:
   - Debugging: `assert` statements can help catch logical errors during development.
   - Input Validation: `assert` can be used to validate input conditions and assumptions.
   - Post-conditions: `assert` can be used to verify that specific conditions hold true after a function or method call.

2. Behavior:
   - If the `expression` is `False`, an `AssertionError` is raised, halting program execution.
   - If the `expression` is `True`, the program continues execution without any impact.
   - The `AssertionError` typically includes the `message` parameter, providing details about the failed assertion.

3. Best Practices:
   - Use `assert` for conditions that should never occur or indicate a bug in the code.
   - Avoid using `assert` for input validation in production code. Instead, use explicit checks and exception handling.



```python
def divide(a, b):
    assert b != 0, "Cannot divide by zero"
    return a / b

result = divide(10, 0)
# Output: AssertionError: Cannot divide by zero
```

In the example, the `assert` statement checks if `b` is not equal to zero before performing division. Since the assertion fails, an `AssertionError` is raised with the provided message.

It's important to note that the `assert` statement is primarily used during development and debugging. In production code, it's recommended to handle exceptions explicitly and provide meaningful error messages to handle exceptional conditions gracefully.


### 2.7.1 Example 6


In [10]:
class Item5:
  #Recieves it self,name , price value and the quanntity
  def __init__(self,namePassed : str ,pricePassed :float ,quantityPassed : int):

    #Validation
    assert pricePassed >= 0 , f"Price {pricePassed} is lower than zero"
    assert quantityPassed >= 0 ,  f"Quantity {quantityPassed} is lower than zero"

    #Assign the properties to the object(self)
    self.name = namePassed
    self.price = pricePassed
    self.quantity = quantityPassed

  def calculatePrice(self) -> float:
    return self.price*self.quantity

item5 = Item5("Laptop",1000,1)



### 2.7.2 Example 7 : Object List

In [11]:
class Item7:
  rate = 0.8
  all  = []
  # Since it is a class attribute It's a common attribute for all
  # Think like , class attributes are like attributes inside a parent object
  # Instance attributes are like attributes inside each child

  def __init__(self,namePassed : str ,pricePassed :float ,quantityPassed : int):

    #Validation
    assert pricePassed >= 0 , f"Price {pricePassed} is lower than zero"
    assert quantityPassed >= 0 ,  f"Quantity {quantityPassed} is lower than zero"

    #Assign the properties to the object(self)
    self.name = namePassed
    self.price = pricePassed
    self.quantity = quantityPassed

    #Update the All list
    Item7.all.append(self)

  def calculatePrice(self) -> float:
    return self.price*self.quantity

  def apply_discount(self):
    self.price = self.price*self.rate

item7_1 = Item7("Laptop",1000,1)
item7_2 = Item7("Phone",250,3)
item7_3 = Item7("Tablet",350,2)
item7_4 = Item7("S-Watch",100,6)

print(Item7.all) # Shows 4 item object array

[<__main__.Item7 object at 0x7dd136e3a590>, <__main__.Item7 object at 0x7dd136e3a140>, <__main__.Item7 object at 0x7dd136e3af80>, <__main__.Item7 object at 0x7dd136e39c30>]


In [12]:
for i in Item7.all:
  print(i.name)

Laptop
Phone
Tablet
S-Watch


### 2.7.3 Example 8 : Object List with \_\_repr\_\_

In [13]:
class Item8:
  rate = 0.8
  all  = []
  # Since it is a class attribute It's a common attribute for all
  # Think like , class attributes are like attributes inside a parent object
  # Instance attributes are like attributes inside each child

  def __init__(self,namePassed : str ,pricePassed :float ,quantityPassed : int):

    #Validation
    assert pricePassed >= 0 , f"Price {pricePassed} is lower than zero"
    assert quantityPassed >= 0 ,  f"Quantity {quantityPassed} is lower than zero"

    #Assign the properties to the object(self)
    self.name = namePassed
    self.price = pricePassed
    self.quantity = quantityPassed

    #Update the All list
    Item8.all.append(self)

  def calculatePrice(self) -> float:
    return self.price*self.quantity

  def apply_discount(self):
    self.price = self.price*self.rate

  '''
  Insted of the  objectID  __repr__ passes an string
  The return string can be customized as required
  The common practice is represent object as it's intance code like 'Item8("Laptop",1000,1)'
  '''
  def __repr__(self):
    return f"Item8('{self.name}',{self.price},{self.quantity})"

item8_1 = Item8("Laptop",1000,1)
item8_2 = Item8("Phone",250,3)
item8_3 = Item8("Tablet",350,2)
item8_4 = Item8("S-Watch",100,6)

print(Item8.all) # Shows 4 item object array

[Item8('Laptop',1000,1), Item8('Phone',250,3), Item8('Tablet',350,2), Item8('S-Watch',100,6)]


## 2.8 Class Methods

A class method is a method that is bound to the class rather than an instance of the class. It is defined using the `@classmethod` decorator and can be accessed using either the class name or an instance of the class. Class methods have access to the class itself and can modify class-level attributes or perform operations that are relevant to the class as a whole. Here are some key points about class methods:

1. **Definition and Syntax:**
   - Class methods are defined using the `@classmethod` decorator before the method definition.
   - The first parameter of a class method is conventionally named `cls` (short for "class"), which refers to the class itself.
   - Class methods are typically defined within the class body but outside of any instances or instance methods.

2. **Access:**
   - Class methods can be accessed using the class name or an instance of the class.
   - When accessed through the class name, the `cls` parameter is automatically passed to the method.
   - When accessed through an instance, the instance is automatically passed as the `cls` parameter.

3. **Purpose:**
   - Class methods are often used to define alternative constructors or provide utility methods related to the class.
   - They can be used to modify class attributes or perform operations that involve the class as a whole.






### 2.8.1 Example 9

In [14]:
class Circle:
    pi = 3.14159  # Class attribute

    def __init__(self, radius):
        self.radius = radius  # Instance attribute

    @classmethod
    def from_diameter(cls, diameter):
        radius = diameter / 2
        return cls(radius)

    def calculate_area(self):
        return self.pi * self.radius * self.radius

circle1 = Circle(5)
circle2 = Circle.from_diameter(10)

print(circle1.calculate_area())  # Output: 78.53975
print(circle2.calculate_area())  # Output: 78.53975

78.53975
78.53975


```python
class Item8:
  rate = 0.8
  all  = []
  def __init__(self,namePassed : str ,pricePassed :float ,quantityPassed : int):

    #Validation
    assert pricePassed >= 0 , f"Price {pricePassed} is lower than zero"
    assert quantityPassed >= 0 ,  f"Quantity {quantityPassed} is lower than zero"

    self.name = namePassed
    self.price = pricePassed
    self.quantity = quantityPassed

    Item8.all.append(self)

  def calculatePrice(self) -> float:
    return self.price*self.quantity

  def apply_discount(self):
    self.price = self.price*self.rate

  # Create objects from CSV ~> used classs method since it's a utility
  @classmethod
  def instantiateFromCSV(cls):

    with open('items.csv','r') as f:
      reader = csv.DictReader(f)
      items = list(reader)

    for i in items:
      Item8(
        name = i.get('name'),
        price = float(i.get('price')),
        quantity = int(i.get('quantity')),
      )

  def __repr__(self):
    return f"Item8('{self.name}',{self.price},{self.quantity})"


#Call the class method
Item8.instantiateFromCSV()
print(Item8.all) # Shows 4 item object array

```

## 2.9 Static methods

Static method is a method that belongs to a class but doesn't have access to the instance or class itself. It is defined using the `@staticmethod` decorator and can be accessed using either the class name or an instance of the class. Static methods are not bound to any specific instance or class state and are primarily used for utility functions or operations that don't require access to instance or class attributes. Here are some key points about static methods:

1. Definition and Syntax:
   - Static methods are defined using the `@staticmethod` decorator before the method definition.
   - Unlike regular methods, static methods don't take any special parameters such as `self` or `cls`.
   - Static methods are typically defined within the class body but outside of any instances or instance methods.

2. Access:
   - Static methods can be accessed using the class name or an instance of the class.
   - When accessed through the class name, no special parameters are automatically passed.
   - When accessed through an instance, no automatic instance-related parameters are passed.

3. Purpose:
   - Static methods are commonly used for utility functions or operations that don't require access to instance or class attributes.
   - They are not specific to any particular instance and do not modify or access instance or class state.


|                   | Class Method                                          | Static Method                                         |
|-------------------|-------------------------------------------------------|-------------------------------------------------------|
| Definition        | Decorated with `@classmethod`                        | Decorated with `@staticmethod`                        |
| Access            | Accessed using the class name or instance             | Accessed using the class name or instance             |
| Parameters        | First parameter conventionally named `cls`            | No special parameters                                 |
| Instance Access   | Has access to class and instance attributes           | Does not have access to class or instance attributes   |
| Class Access      | Has access to class attributes                        | Does not have access to class attributes              |
| Purpose           | Operates on class or instance attributes             | Utility functions or operations not requiring state   |
| Modification      | Can modify class attributes                          | Cannot modify class attributes                        |
| Inheritance       | Can be overridden by subclasses                      | Can be overridden by subclasses                      |
| Implicit Self     | Receives the class as the first parameter (`cls`)     | No implicit self parameter                            |
| Dependency        | Can depend on class or instance state                 | Does not depend on class or instance state            |
| Code Organization | Group related functionality within a class            | Group utility functions within a class                |
| Common Use Cases  | Alternative constructors, class-level operations     | Utility functions, independent operations             |


### 2.9.1 Static Method

In [15]:
class MathUtils:
    @staticmethod
    def add(a, b):
        return a + b

    @staticmethod
    def multiply(a, b):
        return a * b

result1 = MathUtils.add(5, 3)
result2 = MathUtils.multiply(4, 6)

print(result1)  # Output: 8
print(result2)  # Output: 24

8
24


## 2.10 Inheritance

Inheritance is a fundamental concept in object-oriented programming (OOP) that allows classes to inherit attributes and methods from **parent classes**. It promotes code reuse, modularity, and allows for the creation of hierarchical relationships between classes. Inheritance enables the creation of specialized classes (child or derived classes) that inherit and extend the functionality of a more general class (parent or base class).

1. **Class Hierarchy:**
   - Inheritance forms a class hierarchy where child classes inherit attributes and methods from parent classes.
   - Parent classes are also known as base classes or superclasses, while child classes are referred to as derived classes or subclasses.

2. **Syntax:**
   - In Python, inheritance is declared by specifying the parent class in parentheses after the child class name when defining the class.
   - The child class inherits all attributes and methods defined in the parent class.

3. **Single Inheritance:**
   - Python supports single inheritance, where a class can inherit from only one parent class.
   - Child classes can access and use the attributes and methods of the parent class as if they were defined in the child class itself.

4. **Overriding Methods:**
   - Child classes can override methods inherited from the parent class by redefining them in the child class.
   - When a method is called on an instance of the child class, the overridden method in the child class is executed instead of the parent class method.

5. **Accessing Parent Class:**
   - Child classes can access the attributes and methods of the parent class using the `super()` function.
   - The `super()` function provides a way to call parent class methods and access parent class attributes from within the child class.

6. **Inheritance Levels:**
   - Inheritance can be hierarchical, allowing for multiple levels of inheritance.
   - A child class can become a parent class for another class, forming a chain of inheritance.

7. **Benefits of Inheritance:**
   - Code Reusability: Inheritance promotes code reuse by allowing child classes to inherit and reuse the functionality of parent classes.
   - Modularity: Inheritance helps in creating modular code by organizing related classes into a hierarchy.
   - Polymorphism: Inheritance supports polymorphism, where objects of different classes can be used interchangeably if they are related through inheritance.





###2.10.1 Example 10

In [16]:
class Animal:
    def __init__(self, name):
        self.name = name

    def speak(self):
        print("The animal speaks.")

class Dog(Animal):
    def __init__(self, name, breed):
        super().__init__(name)
        self.breed = breed

    def speak(self):
        print("The dog barks.")

animal = Animal("Generic Animal")
dog = Dog("Buddy", "Labrador")

animal.speak()  # Output: The animal speaks.
dog.speak()     # Output: The dog barks.


The animal speaks.
The dog barks.


In the example, the `Animal` class is the parent class, and the `Dog` class is the child class that inherits from `Animal`. The `Dog` class overrides the `speak()` method of the `Animal` class with its own implementation. When `speak()` is called on the `animal` object, it executes the method from the `Animal` class. When `speak()` is called on the `dog` object, it executes the overridden method from the `Dog` class.


### 2.10.2 Example 11

In [17]:
# Base or the Parent Class
class Item11:
  rate = 0.8
  all  = []

  def __init__(self,namePassed : str ,pricePassed :float ,quantityPassed : int):

    assert pricePassed >= 0 , f"Price {pricePassed} is lower than zero"
    assert quantityPassed >= 0 ,  f"Quantity {quantityPassed} is lower than zero"

    self.name = namePassed
    self.price = pricePassed
    self.quantity = quantityPassed

    Item11.all.append(self)

  def calculatePrice(self) -> float:
    return self.price*self.quantity

  def apply_discount(self):
    self.price = self.price*self.rate

  def __repr__(self):
    return f"{self.__class__.__name__}('{self.name}',{self.price},{self.quantity})"

item11_1 = Item11("Laptop",1000,1)
item11_2 = Item11("Phone",250,3)
item11_3 = Item11("Tablet",350,2)
item11_4 = Item11("S-Watch",100,6)

print(Item11.all) # Shows 4 item object array

[Item11('Laptop',1000,1), Item11('Phone',250,3), Item11('Tablet',350,2), Item11('S-Watch',100,6)]


In [18]:
#Inherited class to add damaged Items

class damagedItems(Item11):
  all = []
  def __init__(self, namePassed: str, pricePassed: float, quantityPassed: int , brokenItemsPassed : int):
    #  Call to super function to have access all the atributes and methods in the parent clasas
    super().__init__(namePassed, pricePassed, quantityPassed)

    # Run validation for new arguments which are unique to the child class
    assert brokenItemsPassed >= 0 , f"Broken phones {brokenItemsPassed} invalid"

    # Assign new uniqe parameters to the child object
    self.brokenItems = brokenItemsPassed

    # Update all list
    damagedItems.all.append(self)


item11_6 = damagedItems("Laptop_Broken",1000,1,1)
item11_7 = damagedItems("Phone_Broken",250,3,1)
item11_8 = damagedItems("Tablet_Broken",350,2,1)
item11_9 = damagedItems("S-Watch_Broken",100,6,1)

# Run
print(item11_6.calculatePrice())
item11_6.apply_discount()
print(item11_6.calculatePrice())

1000
800.0


In [19]:
print(Item11.all)

[Item11('Laptop',1000,1), Item11('Phone',250,3), Item11('Tablet',350,2), Item11('S-Watch',100,6), damagedItems('Laptop_Broken',800.0,1), damagedItems('Phone_Broken',250,3), damagedItems('Tablet_Broken',350,2), damagedItems('S-Watch_Broken',100,6)]


In [20]:
print(damagedItems.all)

[damagedItems('Laptop_Broken',800.0,1), damagedItems('Phone_Broken',250,3), damagedItems('Tablet_Broken',350,2), damagedItems('S-Watch_Broken',100,6)]


# 3.0 Numpy Library

## 3.1 Introduction

### 3.1.1 Introduction to Numpy

NumPy (Numerical Python) is a powerful library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays efficiently. NumPy is a fundamental building block for data analysis, scientific computing, and machine learning tasks in Python.

### 3.1.2 What is NumPy?

NumPy is an open-source library that extends Python's capabilities to handle arrays and numerical operations with ease. It was created to address the limitations of Python's built-in data structures and to provide fast, memory-efficient operations on large datasets. The core data structure in NumPy is the "ndarray" (n-dimensional array), which allows for element-wise operations and broadcasting. NumPy also supports various data types and functions to work with these arrays efficiently.

### 3.1.3 Why NumPy ?

NumPy offers several compelling reasons to use it for numerical computing tasks:

- **Performance:** NumPy is implemented in C and offers highly optimized array operations, making it much faster than traditional Python lists when handling large datasets.

- **Memory Efficiency:** NumPy arrays are more memory-efficient compared to Python lists, which can be critical when dealing with huge datasets.

- **Broadcasting:** NumPy enables broadcasting, which allows operations on arrays of different shapes and sizes, making code concise and readable.

- **Mathematical Functions:** NumPy provides a wide range of mathematical functions for array operations, linear algebra, statistics, and more.

- **Integration with Other Libraries:** NumPy seamlessly integrates with various data science and machine learning libraries in the Python ecosystem.

### 3.1.4 Getting started with NumPy

**Installing NumPy**

Installing NumPy is straightforward and can be done using Python's package manager, pip. Simply open a terminal or command prompt and execute the following command:

```
pip install numpy
```

Ensure that you have an active internet connection, and NumPy will be downloaded and installed on your system.

**Getting Started with NumPy Arrays**

To start using NumPy, you need to import the library in your Python script or interactive session:

```python
import numpy as np
```

With NumPy imported, you can now create NumPy arrays and perform various operations on them. The first step is often to create an array:

```python
# Creating a NumPy array from a list
arr = np.array([1, 2, 3, 4, 5])

# Creating a multi-dimensional array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

## 3.2 NumPy Arrays

NumPy provides powerful capabilities for creating and manipulating arrays.

### 3.2.1  Creating NumPy Arrays

1. Creating an array from a Python list:

In [21]:
import numpy as np

list_data = [1, 2, 3, 4, 5]
numpy_array = np.array(list_data)
print(numpy_array)

[1 2 3 4 5]


2. Creating a 2D array from nested lists:


In [22]:
nested_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
numpy_2d_array = np.array(nested_lists)
print(numpy_2d_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3. Creating an array of zeros with a specified shape:

In [23]:
zeros_array = np.zeros((3, 4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


4. Creating an array of ones with a specified shape:

In [24]:
ones_array = np.ones((2, 3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


5. Creating an array with a specified range of values:

In [25]:
range_array = np.arange(0, 10, 2)
print(range_array)

[0 2 4 6 8]


6. Creating an array with equally spaced values:

In [26]:
spaced_array = np.linspace(0, 1, 5)
print(spaced_array)

[0.   0.25 0.5  0.75 1.  ]


7. Creating a 3x3 identity matrix:


In [27]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8. Creating a random 2x3 array:

In [28]:
random_array = np.random.rand(2, 3)
print(random_array)

[[0.6961599  0.10489049 0.01912209]
 [0.59554094 0.32394732 0.57287567]]


9. Creating an array with random integers between a range:


In [29]:
random_integers = np.random.randint(1, 10, (3, 3))
print(random_integers)

[[2 2 3]
 [8 4 7]
 [8 7 6]]


10. Creating an array with repeated values:

In [30]:
repeated_values = np.repeat(5, 5)
print(repeated_values)

[5 5 5 5 5]


### 3.2.2 Indexing and Slicing

1. Accessing a single element from an array:


In [31]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[3])

4


2. Slicing a 1D array:

In [32]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])

[2 3 4]


3. Indexing and slicing a 2D array:

In [33]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)
print(arr_2d[1, 2])
print(arr_2d[0:2, 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[2 3]
 [5 6]]


4. Using negative indices for reverse indexing:

In [34]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[-1])

5


5. Assigning new values to array elements using indexing:


In [35]:
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 10
print(arr)

[ 1  2 10  4  5]


6. Boolean indexing to filter array elements:

In [36]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 30
print(arr[mask])

[40 50]


7. Indexing with a list of integers:

In [37]:
arr = np.array([1, 2, 3, 4, 5])
indices = [0, 2, 4]
print(arr[indices])

[1 3 5]


8. Using "np.ix_" for advanced indexing:

In [38]:
arr = np.array([1, 2, 3, 4, 5])
rows_to_select = [True, False, True, False, False]
print(arr[np.ix_(rows_to_select)])

[1 3]


9. Combining Boolean masks with logical operators:

In [39]:
arr = np.array([10, 20, 30, 40, 50])
mask1 = arr > 20
mask2 = arr < 50
print(arr[mask1 & mask2])

[30 40]


10. Modifying sub-arrays using slicing:

In [40]:
arr = np.array([1, 2, 3, 4, 5])
arr[1:4] = 100
print(arr)

[  1 100 100 100   5]


### 3.2.3 Array Shape and Dimensions

1. Checking the shape of an array:

In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


2. Determining the number of dimensions:

In [42]:
arr = np.array([1, 2, 3])
print(arr.ndim)

1


3. Finding the total number of elements in an array:

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)

6


4. Reshaping a 1D array into a 2D array:

In [44]:
arr = np.arange(1, 7)
print(arr)
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


5. Flattening a 2D array into a 1D array:

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
print(flattened_arr)

[1 2 3 4 5 6]


6. Raveling a 2D array (similar to flatten but returns a view if possible):

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
raveled_arr = arr.ravel()
print(raveled_arr)

[1 2 3 4 5 6]


7. Adding a new dimension to an existing array:

In [47]:
arr = np.array([1, 2, 3])
print(arr)
new_dimension_arr = arr[:, np.newaxis]
print(new_dimension_arr)

[1 2 3]
[[1]
 [2]
 [3]]


8. Concatenating arrays along a specified axis:

In [48]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)

[1 2 3 4 5 6]


9. Stacking arrays vertically and horizontally:

In [49]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
vertical_stack = np.vstack((arr1, arr2))
horizontal_stack = np.hstack((arr1, arr2.T))
print(vertical_stack)
print(horizontal_stack)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


### 3.2.4 Reshaping and Transposing Arrays

1. Reshaping a 1D array to a 2D array with specified dimensions:

In [50]:
arr = np.arange(1, 7)
reshaped_arr = np.reshape(arr, (2, 3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


2. Reshaping an array using "-1" as a placeholder:

In [51]:
arr = np.arange(1, 13)
reshaped_arr = np.reshape(arr, (3, -1))
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


3. Transposing an array using "transpose" function:

In [52]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = np.transpose(arr)
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


4. Transposing an array using "T" attribute:

In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = arr.T
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


5. Swapping axes of a 2D array:

In [54]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
swapped_arr = arr.swapaxes(0, 1)
print(swapped_arr)

[[1 4]
 [2 5]
 [3 6]]


6. Flipping an array horizontally:

In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flipped_arr = np.fliplr(arr)
print(flipped_arr)

[[3 2 1]
 [6 5 4]]


7. Flipping an array vertically:

In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flipped_arr = np.flipud(arr)
print(flipped_arr)

[[4 5 6]
 [1 2 3]]


8. Rolling elements of an array:

In [57]:
arr = np.array([1, 2, 3, 4, 5])
rolled_arr = np.roll(arr, 2)
print(rolled_arr)

[4 5 1 2 3]


9. Rotating elements of an array:

In [58]:
#arr = np.array([1, 2, 3, 4, 5])
#rotated_arr = np.rot90(arr)
#print(rotated_arr)

10. Tiling an array to create a larger array:

In [59]:
arr = np.array([1, 2, 3])
tiled_arr = np.tile(arr, 3)
print(tiled_arr)

[1 2 3 1 2 3 1 2 3]


### 3.2.5 Array Operations and Broadcasting

1. Element-wise arithmetic operations:

In [60]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2
print(addition, subtraction, multiplication, division)

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]


2. Element-wise comparison operations:

In [61]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 2, 1])
greater_than = arr1 > arr2
less_than_or_equal = arr1 <= arr2
equal = arr1 == arr2
print(greater_than, less_than_or_equal, equal)

[False False  True] [ True  True False] [False  True False]


3. Broadcasting with a scalar:

In [62]:
arr = np.array([1, 2, 3])
result = arr + 5
print(result)

[6 7 8]


4. Broadcasting with a 1D array:

In [63]:
arr = np.array([1, 2, 3])
row_vector = np.array([10, 20, 30])
result = arr + row_vector
print(result)

[11 22 33]


5. Broadcasting with a 2D array:

In [64]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_vector = np.array([[10], [20]])
result = arr + column_vector
print(result)

[[11 12 13]
 [24 25 26]]


6. Element-wise square root:

In [65]:
arr = np.array([1, 4, 9])
result = np.sqrt(arr)
print(result)

[1. 2. 3.]


7. Element-wise exponentiation:

In [66]:
arr = np.array([2, 3, 4])
result = np.exp(arr)
print(result)

[ 7.3890561  20.08553692 54.59815003]


8. Element-wise trigonometric functions:

In [67]:
arr = np.array([0, np.pi/2, np.pi])
result_sin = np.sin(arr)
result_cos = np.cos(arr)
result_tan = np.tan(arr)
print(result_sin, result_cos, result_tan)

[0.0000000e+00 1.0000000e+00 1.2246468e-16] [ 1.000000e+00  6.123234e-17 -1.000000e+00] [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


9. Summing elements of an array:

In [68]:
arr = np.array([1, 2, 3, 4, 5])
sum_result = np.sum(arr)
print(sum_result)

15


10. Matrix multiplication:

In [69]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print(result)

[[19 22]
 [43 50]]


## 3.3 Linear Algebra



NumPy linear algebra functions

| Function                      | Structure                                      | Description                                                                                                               |
|-------------------------------|------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------|
| `np.dot(a, b)`                | `np.dot(a, b, out=None)`                      | Compute the dot product of two arrays.                                                                                  |
| `np.matmul(a, b)`             | `np.matmul(a, b, out=None)`                   | Matrix multiplication between two arrays.                                                                                |
| `np.linalg.inv(a)`            | `np.linalg.inv(a)`                            | Compute the (multiplicative) inverse of a square matrix.                                                                 |
| `np.linalg.det(a)`            | `np.linalg.det(a)`                            | Compute the determinant of a square matrix.                                                                              |
| `np.linalg.eig(a)`            | `np.linalg.eig(a)`                            | Compute the eigenvalues and eigenvectors of a square matrix.                                                             |
| `np.linalg.svd(a)`            | `np.linalg.svd(a, full_matrices=True, compute_uv=True, hermitian=False)` | Perform singular value decomposition on a matrix.                                                                  |
| `np.linalg.solve(a, b)`       | `np.linalg.solve(a, b)`                       | Solve a linear matrix equation, `ax = b`, for `x`.                                                                        |
| `np.linalg.lstsq(a, b, rcond=None)` | `np.linalg.lstsq(a, b, rcond=None)`       | Solve linear least-squares problem, `min ||a @ x - b||^2`.                                                                |
| `np.linalg.norm(x, ord=None)` | `np.linalg.norm(x, ord=None, axis=None, keepdims=False)` | Compute the norm of an array, `x`.                                                                                 |
| `np.linalg.qr(a, mode='reduced')` | `np.linalg.qr(a, mode='reduced')`          | Compute the QR decomposition of a matrix.                                                                                |
| `np.linalg.eigh(a, UPLO='L')`  | `np.linalg.eigh(a, UPLO='L', eigvals_only=False)` | Compute eigenvalues and (optionally) eigenvectors of a Hermitian or symmetric matrix.                           |
| `np.linalg.matrix_power(a, n)` | `np.linalg.matrix_power(a, n)`                | Raise a square matrix to the (integer) power `n`.                                                                         |


### 3.3.1 Dot Product

The dot product is a fundamental operation in linear algebra, and NumPy provides a powerful function, `np.dot()`, to perform this operation efficiently.

#### 3.3.1.1 Introduction to Dot Product


The dot product, also known as the scalar product or inner product, is an operation that takes two vectors and returns a scalar value. For two vectors, A and B, the dot product is calculated as:

```
A · B = |A| * |B| * cos(θ)
```

where `|A|` and `|B|` are the magnitudes (lengths) of vectors A and B, respectively, and θ is the angle between the two vectors.

#### 3.3.1.2 Dot Product in NumPy

In NumPy, the `np.dot()` function is used to compute the dot product of two arrays. The operation is performed element-wise, followed by the summation of the results.

Example 1: Dot Product of 1D Arrays

In [70]:
# 1D arrays
A = np.array([2, 3, 5])
B = np.array([4, 1, 7])

# Calculate the dot product
dot_product = np.dot(A, B)
print("Dot Product of A and B:", dot_product)

Dot Product of A and B: 46


Example 2: Dot Product of 2D Arrays

In [71]:
# 2D arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Calculate the dot product
dot_product = np.dot(A, B)
print("Dot Product of A and B:")
print(dot_product)

Dot Product of A and B:
[[19 22]
 [43 50]]


Example 3 :  Broadcasting in Dot Product

In [72]:
# Broadcasting example
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([2, 3, 4])

# Calculate the dot product with broadcasting
dot_product = np.dot(A, B)
print("Dot Product with Broadcasting:")
print(dot_product)

Dot Product with Broadcasting:
[20 47]


### 3.3.2 Matrix Multiplication

NumPy's `matmul()` function is used to perform matrix multiplication between two arrays. It is a versatile function that can handle both 1D and 2D arrays, making it useful for a wide range of linear algebra computations. The `matmul()` function is equivalent to the `@` operator in Python 3.5 and above.

**Syntax:**
```
numpy.matmul(a, b, out=None)
```

**Parameters:**
- `a`: First input array (matrix) for multiplication.
- `b`: Second input array (matrix) for multiplication.
- `out`: Optional. The output array where the result is stored.

**Return Value:**
- The result of the matrix multiplication between `a` and `b`.

**Note:**
- For 2D arrays, `matmul()` performs matrix multiplication.
- For 1D arrays, `matmul()` behaves like the dot product.


Example 1: Matrix Multiplication (2D arrays)

In [73]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.matmul(A, B)
# Equivalent to: result = A @ B

print(result)

[[19 22]
 [43 50]]


Example 2: Dot Product (1D arrays)

In [74]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

result = np.matmul(A, B)
# Equivalent to: result = A @ B

print(result)

32


Example 3: Broadcasting in matmul()

In [75]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([2, 3])

result = np.matmul(A, B)
# Equivalent to: result = A @ B

print(result)

[ 8 18 28]


Example 4: Output Array with out Parameter

In [76]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

output_array = np.zeros((2, 2), dtype=int)

result = np.matmul(A, B, out=output_array)
# Equivalent to: result = np.matmul(A, B)

print(result)

[[19 22]
 [43 50]]


### 3.3.3 Inverse Matrix

In linear algebra, the inverse of a square matrix A is denoted as A^(-1). When a square matrix is multiplied by its inverse, the result is the identity matrix, denoted as I. NumPy provides the `np.linalg.inv()` function to calculate the inverse of a square matrix.

**Syntax:**
```
numpy.linalg.inv(a)
```

**Parameters:**
- `a`: The input square matrix for which the inverse is to be calculated.

**Return Value:**
- The inverse matrix of `a`.

**Note:**
- The input matrix `a` must be square (i.e., have the same number of rows and columns).
- Not all matrices have an inverse. If `a` is singular or nearly singular, the `np.linalg.inv()` function may raise a `LinAlgError`.


Example 1: Calculate Inverse of a 2x2 Matrix

In [77]:
A = np.array([[1, 2], [3, 4]])

inverse_A = np.linalg.inv(A)

print(inverse_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


Example 2: Calculate Inverse of a 3x3 Matrix

In [78]:
B = np.array([[2, 1, 3], [4, 2, 1], [3, 4, 2]])

inverse_B = np.linalg.inv(B)

print(inverse_B)

[[ 0.   0.4 -0.2]
 [-0.2 -0.2  0.4]
 [ 0.4 -0.2  0. ]]


Example 3: Singular Matrix

In [79]:
C = np.array([[1, 2], [2, 4]])

try:
    inverse_C = np.linalg.inv(C)
    print(inverse_C)
except np.linalg.LinAlgError:
    print("Matrix C is singular. Inverse does not exist.")

Matrix C is singular. Inverse does not exist.


**Note on singular and non-singular marixes**

In linear algebra, a square matrix is called "singular" if it does not have an inverse.(i.e. No solutions , incomplete equation combinations) In other words, a matrix A is singular if there is no matrix B such that the product of A and B (AB) is the identity matrix (I). If a matrix is singular, it cannot be inverted, and attempting to find its inverse will result in an error.

On the other hand, a square matrix that has an inverse is called "non-singular" or "invertible." If a matrix A is non-singular, there exists a matrix B such that AB = BA = I. The inverse of a non-singular matrix A is denoted as A^(-1), and it satisfies the property: A * A^(-1) = A^(-1) * A = I.

Mathematically, for a square matrix A of size (n x n), the conditions for singularity are:

1. If the determinant of A (det(A)) is equal to zero, the matrix A is singular.
2. If the rank of A (rank(A)) is less than n, the matrix A is singular.

A square matrix is non-singular if and only if its determinant is non-zero, and its rank is equal to the number of rows (n).


###3.3.4 Determinent

In NumPy, you can calculate the determinant of a square matrix using the `numpy.linalg.det()` function. This function computes the determinant of a given square matrix.

**Syntax:**
```
numpy.linalg.det(a)
```

**Parameters:**
- `a`: The input square matrix for which the determinant is to be calculated.

**Return Value:**
- The determinant of the input matrix `a`.

**Note:**
- The input matrix `a` must be square (i.e., have the same number of rows and columns).


Example:


In [80]:
# 3x3 matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the determinant
det_A = np.linalg.det(A)

print(det_A)

0.0


In this example, the determinant of the matrix `A` is computed and found to be `0.0`. Since the determinant is zero, the matrix `A` is singular, and it does not have an inverse.

### 3.3.5  Eigenvalues and Eigenvectors of a Square Matrix

In NumPy, to compute the eigenvalues and eigenvectors of a square matrix using the `numpy.linalg.eig()` function.

**Syntax:**
```
numpy.linalg.eig(a)
```

**Parameters:**
- `a`: The input square matrix for which the eigenvalues and eigenvectors are to be calculated.

**Return Value:**
- `eigenvalues`: An array containing the eigenvalues of the input matrix `a`.
- `eigenvectors`: An array containing the eigenvectors of the input matrix `a`. Each column in the array represents an eigenvector.

**Note:**
- The input matrix `a` must be square (i.e., have the same number of rows and columns).


Example 1: Eigenvalues and Eigenvectors of a 2x2 Matrix

In [81]:
A = np.array([[2, -1], [4, 1]])

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[1.5+1.93649167j 1.5-1.93649167j]

Eigenvectors:
[[0.1118034 +0.4330127j 0.1118034 -0.4330127j]
 [0.89442719+0.j        0.89442719-0.j       ]]


Example 2: Eigenvalues and Eigenvectors of a 3x3 Matrix

In [82]:
# 3x3 matrix
B = np.array([[1, 2, 3], [0, 4, 5], [0, 0, 6]])

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(B)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[1. 4. 6.]

Eigenvectors:
[[1.         0.5547002  0.51084069]
 [0.         0.83205029 0.79818857]
 [0.         0.         0.31927543]]
